#!/usr/bin/env python
import re, os
import tweepy
from subprocess import *

CONSUMER_KEY = 'jNyV9FHa6rwZG2RmfFfLjw'
CONSUMER_SECRET = 'HJjWidPugUahDM8sY9XcrQSoN9LaJAVCzxq5T9jp68'
if os.path.isfile('~/.pypmon'): 
    authFile = open('~/.pypmon').readlines()
    ACCESS_KEY = authFile[0]
    ACCESS_SECRET = authFile[1]
else:
    ACCESS_KEY, ACCESS_SECRET = authorize()
    open('~/.pypmon').write('%s\n%s' % (ACCESS_KEY, ACCESS_SECRET)).close()

INTERFACE = 'wlan0'

ADDR_RE = re.compile('inet addr.+? ', re.M)

def getIp(interface=INTERFACE):
    ifconfig = Popen("ifconfig %s" % interface, shell=True, stdout=PIPE).stdout
    output = ifconfig.read()
    ip = ADDR_RE.findall(output)
    if len(ip) > 0:
        return ip[0][10:-1]
    else:
        return None

def authorize():
    auth = tweepy.OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET)
    auth_url = auth.get_authorization_url()
    print 'Please authorize: ' + auth_url
    verifier = raw_input('PIN: ').strip()
    auth.get_access_token(verifier)
    accessKey = auth.access_token.key
    accessSecret = auth.access_token.secret
    print "ACCESS_KEY = '%s'" % accessKey
    print "ACCESS_SECRET = '%s'" % accessSecret
    return accessKey, accessSecret
    

def sendIp(self):
    message = '''My current IP is %s. '''

if __name__ == '__main__':
    print getIp('lo')

