#!/usr/bin/env python
import re, os, urllib2, time
import tweepy
from subprocess import *

CONSUMER_KEY = 'jNyV9FHa6rwZG2RmfFfLjw'
CONSUMER_SECRET = 'HJjWidPugUahDM8sY9XcrQSoN9LaJAVCzxq5T9jp68'

AUTH_FILE = os.path.expanduser('~/.pypmon')

INTERFACE = 'wlan0'

ADDR_RE = re.compile('inet addr.+? ', re.M)

def getWanIp():
    #get the ip from icanhazip.com
    ip = urllib2.urlopen('http://icanhazip.com/').read()
    return ip.strip()

def getIp(interface=INTERFACE):
    ifconfig = Popen("ifconfig %s" % interface, shell=True, stdout=PIPE).stdout
    output = ifconfig.read()
    ip = ADDR_RE.findall(output)
    if len(ip) > 0:
        return ip[0][10:-1]
    else:
        return None

def authorize():
    auth = tweepy.OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET)
    auth_url = auth.get_authorization_url()
    print 'Please authorize: ' + auth_url
    verifier = raw_input('PIN: ').strip()
    auth.get_access_token(verifier)
    accessKey = auth.access_token.key
    accessSecret = auth.access_token.secret
    print "ACCESS_KEY = '%s'" % accessKey
    print "ACCESS_SECRET = '%s'" % accessSecret
    return accessKey, accessSecret
    

def sendIp(ACCESS_KEY, ACCESS_SECRET):
    message = '''LAN IP :  %s - WAN IP : %s - Time : %s seconds since the epoch''' % (getIp(), getWanIp(), time.time())
    auth = tweepy.OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET)
    auth.set_access_token(ACCESS_KEY, ACCESS_SECRET)
    api = tweepy.API(auth)
    api.update_status(message)

if __name__ == '__main__':
    print getIp('lo')
    if os.path.isfile(AUTH_FILE):
        authFile = open(AUTH_FILE).readlines()
        ACCESS_KEY = authFile[0].strip()
        ACCESS_SECRET = authFile[1].strip()
    else:
        ACCESS_KEY, ACCESS_SECRET = authorize()
        authFile = open(AUTH_FILE, 'w')
        authFile.write('%s\n%s' % (ACCESS_KEY, ACCESS_SECRET))
        authFile.close()
    sendIp(ACCESS_KEY, ACCESS_SECRET)
